blank_issues_enabled: false
contact_links:
  - name: Docs
    url: https://swap-dk.github.io/SwapDK
    about: Read the documentation to learn how to use SwapDK.
  - name: Contact
    url: https://swapdk.com/
    about: Contact the team to learn more about SwapDK.
  - name: Discord
    url: https://discord.gg/swapdk
    about: Join the community to get support and stay updated.
