name: Check Token List

on:
  workflow_dispatch:
  schedule:
    - cron: "0 9 * * 1"

jobs:
  check-and-update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}

      - name: Setup Repo
        uses: ./tools/github/setup-repo

      - name: Generate new token list
        id: commit
        run: |
          bun build:ci
          bun generate:tokens
          changes=$(git status -s | wc -l | xargs)
          echo "numberOfChangedFiles=$changes" >> $GITHUB_OUTPUT

          if [ $changes != 0 ]; then
            echo "Changed files found, pushing to bot/token-list-update"

            git config --global user.email "swapdk@users.noreply.github.com"
            git config --global user.name "swapdk"
            git checkout -b bot/token-list-update
            git add .
            git commit -m "ðŸ¤–: automatic tokenlist update"
            git push origin bot/token-list-update --force
          else
            echo "No changes found"
          fi

      - name: Open Pull Request
        if: steps.commit.outputs.numberOfChangedFiles > 0
        uses: devops-infra/action-pull-request@34a042a4b1cc7073122455aee6ffc76ccf9d9039
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          source_branch: bot/token-list-update
          target_branch: develop
          title: "[Bot] Update Token List"
          label: token-list
          get_diff: true
